### ISSUE TITLE
Insert date is not possible

### ISSUE THREAD

**Issue by JoergHoffmannatGitHub** [JoergHoffmannatGitHub/Family.Show#3]
**Describe the bug**
Inserting a date with keyboard (number by number) is not possible.

**To Reproduce**
1. Go to 'Edit Details'
2. Click on 'Date of Birth' - any Textbox with a date will do
3. start typing
4. after typing the first number the date changes to 01.01.0001

**Expected behavior**
A date typing number by number shall be possible.

**Screenshots**
![DateOfDeath](https://github.com/JoergHoffmannatGitHub/Family.Show/assets/119740874/7ea06830-78b0-49c0-9bc9-918ba28a2ada)

**Desktop (please complete the following information):**
 - Version
v5.0.0-alpha1

**Comment by deantpage** [comment]
I just changed the bindings to use UpdateSourceTrigger=LostFocus wherever the DateFormattingConverter is used. The DateFormattingConverter code needs a re-write but this change allows me to actually enter dates for now.

**Comment by JoergHoffmannatGitHub** [comment]
Works like a charm. I will test it further.

**Comment by JoergHoffmannatGitHub** [comment]
DateFormattingConverter is working with UpdateSourceTrigger=LostFocus now.
